@host = https://localhost:10000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI2ODUzYmExYi03NzUzLTQ1ZmEtYjlhMy0yNjEwZmIyZGU3MjUiLCJlbWFpbCI6InRvQG1pc3RlcmFidmlyLnJ1IiwicHJlZmVycmVkX3VzZXJuYW1lIjoibWlzdGVyYWJ2aXIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiaXNzIjoiaXNzdWVyLXRlc3QiLCJhdWQiOlsiYXVkaWVuY2UtdGVzdCIsImF1ZGllbmNlLXRlc3QiXSwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9leHBpcmF0aW9uIjoiOC8xLzIwMjQgMjoxMDoyNSBBTSIsIm5iZiI6MTcyMjQyNDIyNSwiZXhwIjoxNzIyNDY3NDI1fQ.4ga-IToGYj1O3sEaHhv7MEQbIdUJYzN3kRq6dlkNWeY
@code = 5ef055

POST {{host}}/users/register HTTP/1.1
Content-Type: application/json

{
    "username" : "misterabvir",
    "email" : "to@misterabvir.ru",
    "password" : "Qwer!234"
}

###
POST {{host}}/users/verify-code HTTP/1.1
Content-Type: application/json

{
    "email" : "to@misterabvir.ru",
    "code" : "{{code}}"
}

### 
POST {{host}}/users/login HTTP/1.1
Content-Type: application/json

{
    "email" : "to@misterabvir.ru",
    "password" : "Qwer!234"
}

### 

GET {{host}}/test-qu2
Authorization: Bearer {{token}}
###
